In [3]:
import pandas as pd
import numpy as np
from word2number import w2n
from sklearn import linear_model

In [4]:
df =pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
# getting the whole value
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

## Filling the NAN values with the median

In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
reg=linear_model.LinearRegression()


## Traing the model using the independent variable to get the target variable

In [8]:
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [9]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
reg.intercept_

221323.00186540408

In [11]:
reg.predict([[3000,3,40]])

C:\Users\Mr bones\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [12]:
112.06244194*3000 + 23388.88007794* 3 + -3231.71790863*40 +221323.00186540408


498408.2515740241

#### HR analysis with multiple variable linear regression

In [13]:
df2 =pd.read_csv("hiring.csv")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

## Rename the headers 

In [14]:
df2.rename(columns={"test_score(out of 10)": "test_score","interview_score(out of 10)" :"interview_score",
                   "salary($)" :"salary"})

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

## Convert words to numbers 

In [15]:
df2.experience = df2.experience.fillna("zero").astype(str)
                                                      
def convert_word_to_num(word):
    try:
        return w2n.word_to_num(word)
    except ValueError:
        return None  # or handle invalid words as needed

# Convert the 'experience' column
df2["experience"] = df2["experience"].apply(convert_word_to_num)
df2


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

## FIll the null values

In [32]:
test_score_median = df2['test_score(out of 10)'].median()
test_score_median

# fill the median to the null value
df2['test_score(out of 10)']=df2['test_score(out of 10)'].fillna(test_score_median)

# Rename the columns
Updated_test=df2.rename(columns={"test_score(out of 10)":"test_score","interview_score(out of 10)":"interview_score",
                    "salary($)":"salary"})
Updated_test

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

## Training the model

In [30]:
Reg =linear_model.LinearRegression() 

In [34]:
Reg.fit(Updated_test[["experience","test_score","interview_score"]], Updated_test.salary)

LinearRegression()

In [35]:
reg.predict([[2,8,7]])

C:\Users\Mr bones\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([386036.14201237])